server:
  port: 9000

spring:
  output:
    # Console Color 표시
    ansi:
      enabled: ALWAYS

  kafka:
    producer:
      bootstrap-servers: localhost:9092

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher